name: "Detect Changed Connectors"
description: "Detects changed connectors between the base commit and the latest commit."
inputs:
  base_commit:
    description: "Base commit to compare changes against"
    required: true
  head_commit:
    description: "Head commit (latest commit) in the PR or push"
    required: true
outputs:
  connectors_list:
    description: "List of changed connectors"
    value: ${{ steps.detect.outputs.connectors_list }}

runs:
  using: "composite"
  steps:
    - name: Detect Changed Connectors
      id: detect
      shell: bash
      run: |
        echo "Comparing commits: ${{ inputs.base_commit }} -> ${{ inputs.head_commit }}"
        
        # Detect changed connectors
        CHANGED_DIRS=$(git diff --name-only "${{ inputs.base_commit }}" "${{ inputs.head_commit }}" | grep '^airbyte-integrations/connectors/' | cut -d/ -f3 | sort -u || true)

        if [[ -z "$CHANGED_DIRS" ]]; then
          echo "⚠️ No changed connectors detected."
          echo "connectors_list=" >> $GITHUB_ENV
        else
          echo "Changed connectors: $CHANGED_DIRS"
          echo "connectors_list=$CHANGED_DIRS" >> $GITHUB_ENV
        fi
