name: Canonical CI

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple command
        run: echo "This is a test"
