name: Canonical CI

on:
  pull_request:
    branches:
      - develop
      - staging
      - master

jobs:
  fail_on_protected_path_changes:
    name: "Check fork do not change protected paths "
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check for changes in protected paths
        id: check_for_changes_in_protected_paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            protected_paths:
              - 'airbyte-ci/**'

      - name: Fail if changes in protected paths
        if: steps.check_for_changes_in_protected_paths.outputs.protected_paths == 'true'
        run: |
          echo "The fork has changes in protected paths. This is not allowed."
          exit 1

  format_check:
    # IMPORTANT: This name must match the require check name on the branch protection settings
    name: "Check for formatting errors"
    if: github.event.pull_request.head.repo.fork == true
    environment: community-ci-auto
    runs-on: community-tooling-test-small
    needs: fail_on_protected_path_changes
    timeout-minutes: 30
    env:
      MAIN_BRANCH_NAME: "master"
    steps:
      # This checkouts a fork which can contain untrusted code
      # It's deemed safe as the formatter are not executing any checked out code
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      # This will sync the .github folder of the main repo with the fork
      # This allows us to use up to date actions and CI logic from the main repo
      - name: Pull .github folder and internal packages from main repository
        id: pull_github_folder
        run: |
          git remote add main https://github.com/airbytehq/airbyte.git
          git fetch main ${MAIN_BRANCH_NAME}
          git checkout main/${MAIN_BRANCH_NAME} -- .github
          git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci

  check_connector_version:
    name: Check connector version
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    steps:
      - name: Check connector version changed
        id: version-check
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == *"Dockerfile"* ]]; then
              if grep -q 'LABEL io.airbyte.version' $FILE; then
                NEW_VERSION=$(grep 'LABEL io.airbyte.version' $FILE | cut -d'=' -f2 | tr -d '"' | tr -d ' ')
                BASE_BRANCH=${{ github.base_ref }}
                git fetch origin $BASE_BRANCH
                BASE_VERSION=$(git show origin/$BASE_BRANCH:$FILE | grep 'LABEL io.airbyte.version' | cut -d'=' -f2 | tr -d '"' | tr -d ' ')
                if [ "$NEW_VERSION" == "$BASE_VERSION" ]; then
                  echo "Error: Connector version has not changed in $FILE"
                  exit 1
                fi
              fi
            fi
              done
